// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8KrENAVZ4yZoiBIR5oPNhjHWHRq7A1E',
    appId: '1:625729285793:web:b52510ceac387d75f44ae0',
    messagingSenderId: '625729285793',
    projectId: 'pfeproject-3c466',
    authDomain: 'pfeproject-3c466.firebaseapp.com',
    storageBucket: 'pfeproject-3c466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAgQblJ-jMsl4WCsc62vXBZWWR6zzFYM',
    appId: '1:625729285793:android:8ce92bb6150e7bfdf44ae0',
    messagingSenderId: '625729285793',
    projectId: 'pfeproject-3c466',
    storageBucket: 'pfeproject-3c466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFF9GQFW4GtTMOJSgRimUGbUGJjy5HBc',
    appId: '1:625729285793:ios:de6a036445393442f44ae0',
    messagingSenderId: '625729285793',
    projectId: 'pfeproject-3c466',
    storageBucket: 'pfeproject-3c466.appspot.com',
    iosBundleId: 'com.example.flutterApplication12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFF9GQFW4GtTMOJSgRimUGbUGJjy5HBc',
    appId: '1:625729285793:ios:d7580c9e635bf4d1f44ae0',
    messagingSenderId: '625729285793',
    projectId: 'pfeproject-3c466',
    storageBucket: 'pfeproject-3c466.appspot.com',
    iosBundleId: 'com.example.flutterApplication12.RunnerTests',
  );
}
